[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/2022/101-ofn-overview/*"
  to = "/2022/101-ofn-overview/index.html"
  status = 200

[[redirects]]
  from = "/2022/202-node-async/*"
  to = "/2022/202-node-async/index.html"
  status = 200

[[redirects]]
  from = "/2022/203-node-mixed/*"
  to = "/2022/203-node-mixed/index.html"
  status = 200

[[redirects]]
  from = "/2022/20221022/*"
  to = "/2022/20221022/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://openfunction.dev"
  status = 302
  force = true