[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/2022/202-node-async/*"
  to = "/2022/202-node-async/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://www.yuque.com/serviceup"
  status = 302